# Read the Docs configuration file for Zensical projects
# See https://docs.readthedocs.com/platform/latest/intro/zensical.html for details

# Required
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: latest
  jobs:
    install:
      - pip install zensical markdown-include pymdown-extensions
    build:
      html:
        - zensical build
    post_build:
      - mkdir -p $READTHEDOCS_OUTPUT/html/
      - cp --recursive site/* $READTHEDOCS_OUTPUT/html/
