site_name: Programutveckling för Tekniska Tillämpningar
pages:
- Hem: index.md
- Arbetsblad 1: assignment1.md
- Arbetsblad 1 (ENG): assignment1_eng.md
- Arbetsblad 2: assignment2.md
- Arbetsblad 3: assignment3.md
- Arbetsblad 4: assignment4.md
- Arbetsblad 5: assignment5.md
- Slutinlämning: assignment6.md
theme: readthedocs
#markdown_extensions: [codehilite]