site_name: Programutveckling för Tekniska Tillämpningar
pages:
- Hem: index.md
- Arbetsblad 2: assignment2.md
- Arbetsblad 3: assignment3.md
- Arbetsblad 4: assignment4.md
- Arbetsblad 5: assignment5.md
theme: readthedocs
#markdown_extensions: [codehilite]