site_name: Software Development for Technical Applications - VSMN20
nav:
- Home: index.md
- Worksheets (English):
  - Worksheet 1: assignment1_eng.md
  - Worksheet 2: assignment2_eng.md
  - Worksheet 3: assignment3_eng.md
  - Worksheet 4: assignment4_eng.md
  - Worksheet 5: assignment5_eng.md
  - Final hand-in: assignment6.md
- Guides:
  - Installation guide for Windows: installation_guide_windows.md
  - Creating tables with Tabulate: data_in_tables.md
- Links: links.md

theme: 
  name: material
  palette:
    scheme: youtube
    #primary: LU
    #accent: LU
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant    
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - header.autohide

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js  

markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true      
  - meta
